let InfoForUsersAddAndAssignNonActivatedProvision = [
    {
        label: "ESN/SIM",
        value: " ESN: Equipment Serial Number; uniquely identifies equipment and is embedded electronically by the manufacturer. SIM: Subscriber Identity Module; a ''smart'' card installed or inserted into a mobile device containing all subscriber-related data. This facilitates a phone call fromany valid mobile device since the subscriber data is used to complete the call rather than the telephone internal serial number. The SIM number is 15 digits. Motorola phones only have 14 digits so add the number 0 at the end.",
    },
    {
        label: "Model ID",
        value: "Model Name and ID assigned by Maker of the Phone devices. For an e.g. Apple IPHONE has various version of their phone such as IPHONE 4, 5s etc.. These Model Name are added to Vcare Inventory system which generates Unique Model ID for each of them which can be used here for identification & tracking purpose.",
    },
    {
        label: "UICCID",
        value: "A SIM card contains its unique serial number (ICCID). ICCIDs are stored in the SIM cards and are also printed on the SIM card during a personalization process. A full ICCID is 19 or 20 characters.",
    },
    {
        label: "Box",
        value: "Its Unique number given to Bundle of Sim/ESN/Device by Warehouse person for their identifier & tracking purpose",
    },
    {
        label: "MSL/PUK",
        value: "An MSL is a 6-digit code unique to your CDMA device that's necessary to access some of your handset's deeper functions, such as wiping a phone number or manually programming in a new one",
    },
    {
        label: "PUK2",
        value: "A PUK2 is a code used to protect specific actions, e.g. changing the PUK code. If you enter the PIN2 incorrectly too many times the phone will apply a further lock. To unlock will need a PUK2 code",
    },
    {
        label: "SIM Card(Y/N)",
        value: "This field will be marked Y specifically for LTE and GSM devices only where UICCID is available.",
    },
    {
        label: "Selling Price",
        value: "Selling price is the retail price tag of each Phone device/Model/SIM card.",
    },
    {
        label: "Wholesale Price",
        value: "It is a price which cost to company to purchase the Phone device from Vendor.",
    },
    {
        label: "Activation Fee",
        value: "A one-time fee a company charges upon the provision of a new ESN/SIM. The activation fee is intended to compensate the company for the expenses associated with setting up the account with carrier.",
    },  
    {
        label: "PO",
        value: "Purchase Order # are Internal Order # generated by Warehouse for their Sale & Purchase tracking.",
    },  
    {
        label: "SKU",
        value: "A stock keeping unit (SKU) is a product and service identification code for a store or product, often portrayed as a machine-readable bar code that helps track the item for inventory.",
    },   
    {
        label: "BYOD",
        value: "Bring Your Own Device, is simply the practice in which customer using his own mobile devices.",
    },  

]; 
let InfoForUserAddPreActivatedProvision = [
    {
        label: "ESN/SIM",
        value: " ESN: Equipment Serial Number; uniquely identifies equipment and is embedded electronically by the manufacturer. SIM: Subscriber Identity Module; a ''smart'' card installed or inserted into a mobile device containing all subscriber-related data. This facilitates a phone call fromany valid mobile device since the subscriber data is used to complete the call rather than the telephone internal serial number. The SIM number is 15 digits. Motorola phones only have 14 digits so add the number 0 at the end.",
    },
    {
        label: "Model ID",
        value: "Model Name and ID assigned by Maker of the Phone devices. For an e.g. Apple IPHONE has various version of their phone such as IPHONE 4, 5s etc.. These Model Name are added to Vcare Inventory system which generates Unique Model ID for each of them which can be used here for identification & tracking purpose.",
    },
    {
        label: "UICCID",
        value: "A SIM card contains its unique serial number (ICCID). ICCIDs are stored in the SIM cards and are also printed on the SIM card during a personalization process. A full ICCID is 19 or 20 characters.",
    },
    {
        label: "Box",
        value: "Its Unique number given to Bundle of Sim/ESN/Device by Warehouse person for their identifier & tracking purpose",
    },
    {
        label: "MSL/PUK",
        value: "An MSL is a 6-digit code unique to your CDMA device that's necessary to access some of your handset's deeper functions, such as wiping a phone number or manually programming in a new one",
    },
    {
        label: "PUK2",
        value: "A PUK2 is a code used to protect specific actions, e.g. changing the PUK code. If you enter the PIN2 incorrectly too many times the phone will apply a further lock. To unlock will need a PUK2 code",
    },
    {
        label: "SIM Card(Y/N)",
        value: "This field will be marked Y specifically for LTE and GSM devices only where UICCID is available.",
    },
    {
        label: "Selling Price",
        value: "Selling price is the retail price tag of each Phone device/Model/SIM card.",
    },
    {
        label: "Wholesale Price",
        value: "It is a price which cost to company to purchase the Phone device from Vendor.",
    },
    {
        label: "Activation Fee",
        value: "A one-time fee a company charges upon the provision of a new ESN/SIM. The activation fee is intended to compensate the company for the expenses associated with setting up the account with carrier.",
    },  
    {
        label: "PO",
        value: "Purchase Order # are Internal Order # generated by Warehouse for their Sale & Purchase tracking.",
    },  
    {
        label: "SKU",
        value: "A stock keeping unit (SKU) is a product and service identification code for a store or product, often portrayed as a machine-readable bar code that helps track the item for inventory.",
    },    
    {
        label: "Zip Code",
        value: "ZIP Codes are a system of postal codes used by the United States Postal Service",
    },   
    {
        label: "Device ID",
        value: "A device ID (device identification) is a distinctive number associated with a smartphone or similar handheld device. Device IDs are separate from hardware serial numbers.",
    },   
    {
        label: "MSID",
        value: "A mobile station ID (MSID) is a number that is associated with the home service provider and the wireless phone number. This is reprogrammed when the user changes home service providers",
    },   
    {
        label: "BYOD",
        value: "Bring Your Own Device, is simply the practice in which customer using his own mobile devices.",
    },  

];   
let InfoForUsersAddAndActivate = [
    {
        label: "ESN/SIM",
        value: " ESN: Equipment Serial Number; uniquely identifies equipment and is embedded electronically by the manufacturer. SIM: Subscriber Identity Module; a ''smart'' card installed or inserted into a mobile device containing all subscriber-related data. This facilitates a phone call fromany valid mobile device since the subscriber data is used to complete the call rather than the telephone internal serial number. The SIM number is 15 digits. Motorola phones only have 14 digits so add the number 0 at the end.",
    },
    {
        label: "Model ID",
        value: "Model Name and ID assigned by Maker of the Phone devices. For an e.g. Apple IPHONE has various version of their phone such as IPHONE 4, 5s etc.. These Model Name are added to Vcare Inventory system which generates Unique Model ID for each of them which can be used here for identification & tracking purpose.",
    },
    {
        label: "UICCID",
        value: "A SIM card contains its unique serial number (ICCID). ICCIDs are stored in the SIM cards and are also printed on the SIM card during a personalization process. A full ICCID is 19 or 20 characters.",
    },
    {
        label: "Box",
        value: "Its Unique number given to Bundle of Sim/ESN/Device by Warehouse person for their identifier & tracking purpose",
    },
    {
        label: "MSL/PUK",
        value: "An MSL is a 6-digit code unique to your CDMA device that's necessary to access some of your handset's deeper functions, such as wiping a phone number or manually programming in a new one",
    },
    {
        label: "PUK2",
        value: "A PUK2 is a code used to protect specific actions, e.g. changing the PUK code. If you enter the PIN2 incorrectly too many times the phone will apply a further lock. To unlock will need a PUK2 code",
    },
    {
        label: "SIM Card(Y/N)",
        value: "This field will be marked Y specifically for LTE and GSM devices only where UICCID is available.",
    },
    {
        label: "Selling Price",
        value: "Selling price is the retail price tag of each Phone device/Model/SIM card.",
    },
    {
        label: "Wholesale Price",
        value: "It is a price which cost to company to purchase the Phone device from Vendor.",
    },
    {
        label: "Activation Fee",
        value: "A one-time fee a company charges upon the provision of a new ESN/SIM. The activation fee is intended to compensate the company for the expenses associated with setting up the account with carrier.",
    },  
    {
        label: "PO",
        value: "Purchase Order # are Internal Order # generated by Warehouse for their Sale & Purchase tracking.",
    },  
    {
        label: "SKU",
        value: "A stock keeping unit (SKU) is a product and service identification code for a store or product, often portrayed as a machine-readable bar code that helps track the item for inventory.",
    },
    {
        label: "Zip Code",
        value: "ZIP Codes are a system of postal codes used by the United States Postal Service",
    },  
    {
        label: "Device ID",
        value: "A device ID (device identification) is a distinctive number associated with a smartphone or similar handheld device. Device IDs are separate from hardware serial numbers.",
    },     
    {
        label: "BYOD",
        value: "Bring Your Own Device, is simply the practice in which customer using his own mobile devices.",
    },  

];   
let InfoForUsersReprovision = [
    {
        label: "ESN/SIM",
        value: " ESN: Equipment Serial Number; uniquely identifies equipment and is embedded electronically by the manufacturer. SIM: Subscriber Identity Module; a ''smart'' card installed or inserted into a mobile device containing all subscriber-related data. This facilitates a phone call fromany valid mobile device since the subscriber data is used to complete the call rather than the telephone internal serial number. The SIM number is 15 digits. Motorola phones only have 14 digits so add the number 0 at the end.",
    },
    {
        label: "Zip Code",
        value: "ZIP Codes are a system of postal codes used by the United States Postal Service",
    },  
  

]; 
export {InfoForUsersReprovision,InfoForUsersAddAndActivate,InfoForUsersAddAndAssignNonActivatedProvision,InfoForUserAddPreActivatedProvision}