let InfoForUsersGsmBulkUpload = [
    { 
        label:"MEID:", 
        value:"MEID stands for Mobile Equipment Identifier and is a unique identifier for a mobile device. MEID is a form of ESN (Electronic Serial Number). MEID numbers often have multiple formats, MEID HEX and MEID DEC. The HEX value is a mix of letters and numbers and the DEC value is all numbers."
    }  
    ,{ 
        label:"Model ID:", 
        value:"Model Name and ID assigned by Maker of the Phone devices. For an e.g. Apple IPHONE has various version of their phone such as IPHONE 4, 5s etc.. These Model Name are added to Vcare Inventory system which generates Unique Model ID for each of them which can be used here for identification & tracking purpose."
    },{ 
        label:"Box:", 
        value:"Its Unique number given to Bundle of Sim/ESN/Device by Warehouse person for their identifier & tracking purpose"
    } 
    ,{ 
        label:"Selling Price", 
        value:"Selling price is the retail price tag of each Phone device/Model/SIM card."
    } 
    ,{ 
        label:"Wholesale Price:", 
        value:"It is a price which cost to company to purchase the Phone device from Vendor."
    },    
    { 
        label:"Activation Fee:", 
        value:"A one-time fee a company charges upon the provision of a new ESN/SIM. The activation fee is intended to compensate the company for the expenses associated with setting up the account with carrier."
    },  
    { 
        label:"PO:", 
        value:"Purchase Order # are Internal Order # generated by Warehouse for their Sale & Purchase tracking."
    },  
    { 
        label:"BYOD", 
        value:"Bring Your Own Device, is simply the practice in which customer using his own mobile devices."
    }


];   

export {InfoForUsersGsmBulkUpload}